name: Write cached file
description: 'Write cached file'
inputs:
  cache_dir:
    description: 'Root path which contains the files that should be cached'
    required: true
  cache_id:
    description: 'The id of the cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Store in cache
      uses: actions/cache@v3.0.2
      with:
        path: |
          ${{ inputs.cache_dir }}/**/*.dll
          ${{ inputs.cache_dir }}/**/*.lib
          ${{ inputs.cache_dir }}/**/*.so
          ${{ inputs.cache_dir }}/**/*.a
          ${{ inputs.cache_dir }}/**/*.h
          ${{ inputs.cache_dir }}/**/*.hpp
        key: ${{ inputs.cache_id }}-${{ hashFiles('${{ inputs.cache_dir }}/**') }}
    #- name: Store in cache
    #  uses: actions/cache@v2
    #  with:
    #    path: |
    #      '${{ inputs.cache_dir }}/**/*.txt'
    #      '${{ inputs.cache_dir }}/**/*.md'
    #    key: ${{ inputs.cache_id }}-${{ hashFiles('${{ inputs.cache_dir }}/**') }}
